# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: blog-examples

provider:
  name: aws
  runtime: nodejs6.10
  profile: <Proflie_name>
  deploymentBucket: <bucket_name>
  memorySize: 128
  timeout: 10
  role: <role>

# you can overwrite defaults here
  stage: dev
  region: us-west-2
  
functions:
  user-data:
    handler: services/userDataHandler.userDataService